### PR TITLE
read/construct tags by name, ForwardOpen functionality

### PR DESCRIPTION
**Pull request by lly-c232733**
### Integrated (into the Read() method) the ability to construct and read tags by only the tag name

> Updated the readParser to build the RequestPath using the tag name in the case that
> 1. instance ID is not enough information to reference desired tag (UDT member) 
> 2. instance ID is not specified

### Added a "STRING2" type

> As Strings in L8 controller are technically a 'struct' type and per page 42 of documentation bit 15 is set to 1 in the struct case

### Added Rockwell/Allen Bradley documentation

> To enable future developers

### Fixed issue from prior pull request #8 

> specific array indices can now be read by using the same syntax as it appears in Studio5000
> Ex. 'myarray[4]'

### Added to the example script

> all original functionality was retained
> new functionality was tested per the example

'
`NOTE: All original functionality was retained`

### CODE REVIEW

**Comment by lly-c232733** [comment]
Added to this pull request:

### Modified ForwardOpen to allow for longer timeout (128 seconds)
> Changed RPI to 1 second
> 1. CIP documentation states the following about RPI, "The requested packet interval shall be the time between packets requested by the receiving device. The value shall be used to allocate bandwidth at each of the producing nodes. The allocation of bandwidth may have to be adjusted when the actual packet rate or actual packet interval is returned, since it is possible for the two values to differ. The path time-out value at each of the intermediate and target nodes shall also be set to the connection time-out multiplier times the API. The RPI is therefore required for all connections."
> 2. CIP documentation states the following about low priority connected messages (this code is hardcoded to specify that this is a low priority connection), "For low priority, the RPI shall be used to set the path time-out in the intermediate and target nodes. The RPI shall therefore be set to the slowest packet rate expected, which shall preclude having the connection close due to a path time-out. The longer the path time-out, the longer the time required to reclaim resources in the intermediate nodes as a result of faults in the network. Since the low priority is not quantized at any of the nodes, the API shall equal the RPI. To maintain consistency, however, the time-out value shall again be set to the Connection Time-out multiplier times the API."

> Changed RPI timeout multiplier to x128

### Added the ForwardOpenLarge service 
> To allow for CIP packet sizes up to 4002 bytes

**Comment by nicrf** [comment]
It seems to work properly, I tried many type, but I catch two things :
NULL was not implemented and int8, can you add this to Tag.go 
```
func (t *Tag) Int8() int8 {
	io := bufferx.New(t.value)
	var val int8
	io.RL(&val)
	return val
}

func (t *Tag) UInt8() uint8 {
	io := bufferx.New(t.value)
	var val uint8
	io.RL(&val)
	return val
}
```

And
```
func (t *Tag) getValue() interface{} {
	switch t.Type {
	case NULL:
		return nil
	case BOOL:
		return t.Bool()
	case SINT:
		return t.Int8()
	case USINT:
		return t.UInt8()
...```

I will try to add a "array" handler in GetValue.

**Comment by lly-c232733** [comment]
Thank you for the feedback!!

I will make the requested update and recommit to this branch! 

EDIT: it is now updated

**Review by nicrf — APPROVED** [review]

**Comment by lly-c232733** [comment]
Any update on this? @MiguelValentine

**Pull request merged**
